### ISSUE TITLE
problem with wikilink

### ISSUE THREAD

**Issue by Courgetteandratatouille** [c2corg/v6_ui#1727]
On this page https://www.camptocamp.org/routes/53823/fr/tete-des-fetoules-arete-w

In the warning the url on "cotation globale" is https://www.camptocamp.org/%02klzzwxh:0000 but it must be http://www.camptocamp.org/articles/188413/fr/aide-topoguide-cotation-alpine-globale

**Comment by brunobesson** [comment]
I gave you an explanation on the forum. Have you any thoughts about my suggestions? I.e. maybe we could change the wikilink parser to recognize only links of the form `document-type/document-id(/lang(/slug))? Thus, full links that are already eaten by the link parser won't be treated.

Personally, I would suggest we do not support the slug either (OK for the lang, though).

**Comment by Courgetteandratatouille** [comment]
If the slug is used in the real link , i guess it's better to keep it for the seo.

It's a good thing if the parser for internal link recognize only  `document-type/document-id(/lang(/slug)) for the app.

In the app internal and external link are not manage with the same way. For external link the navigator is open, for internal , the app do the job.

**Comment by brunobesson** [comment]
With #1729, we are no more pedantic with wikilinks

**Comment by fbunoz** [comment]
> It's a good thing if the parser for internal link recognize only `document-type/document-id(/lang(/slug)) for the app.

It's better to allow type/id(/lang(/slug))(#anchor)
For instance, in prod this syntax works :
[[articles/108240#montant-de-la-cotisation|cotisation]]
Then in the html the link is /articles/108240#montant-de-la-cotisation , which is translated to https://www.camptocamp.org/articles/108240#montant-de-la-cotisation by the browser.
And the server redirection adds the lang and the slug : https://www.camptocamp.org/articles/108240/fr/camptocamp-association-comment-adherer#montant-de-la-cotisation

_You can see that the anchor link works correctly, but the menu bar masks the sub title and the first line._

**Comment by brunobesson** [comment]
How is the anchor formatted? Similar to slug?

**Comment by brunobesson** [comment]
Anyway, I updated the PR to support anchor in the form `#[a-zA-Z\-]+`

**Comment by fbunoz** [comment]
> How is the anchor formatted? Similar to slug?

The anchor syntax is : #anchor-id
anchor-id is the "id" or "name" attribute of a html tag, then must be respect its syntax.
I don't know exactly the rules, but we can allow alphanum and "-" as for the slug.

**Comment by desnoes** [comment]
@brunobesson : my understanding is that anchors in the form #... have been added to the supported syntaxe. If it is the case, the test is OK. I let you validate this issue.
Note that in this example  (http://www.demov6.camptocamp.org/routes/53823/fr/tete-des-fetoules-arete-w), there is still an issue with a wikilink

**Comment by asaunier** [comment]
> Note that in this example (http://www.demov6.camptocamp.org/routes/53823/fr/tete-des-fetoules-arete-w), there is still an issue with a wikilink

Because wikilinks should not contain the full URL (in that case one should use a standard link), only something like ``articles/1234/...``.
