### ISSUE TITLE
Problems with columns layout

### ISSUE THREAD

**Issue by asaunier** [c2corg/v6_ui#690]
- [x] sorting problem:

There a problem with the columns layout we have just reintroduced in cards listings (eg. advanced search).

For instance with the outings: most recent outings appears in the leftmost column from top to bottom, then the next outings appear in the next column (top to bottom). See for instance:

![sans titre](https://cloud.githubusercontent.com/assets/1192331/19112228/f1c9d142-8b03-11e6-8364-630190f21dc8.png)

This is not very intuitive: users will most likely expect to see the most recent outings on top of the list, whatever the column.

In addition, for the home page feed, if infinite scrolling is used (or with pagination such as a "see more feed" button), older feed items will be added at the bottom.

**Comment by asaunier** [comment]
* [ ] In FF only one card column is displayed (instead of 3 as with Chromium):
![sans titre](https://cloud.githubusercontent.com/assets/1192331/19151662/30f57c66-8bce-11e6-9cd2-9b63edc3ce23.png)

**Comment by loicperrin** [comment]
- [ ] Another problem with columns layout: sometimes the first cards of the column are cut. Example:
![issue690](https://cloud.githubusercontent.com/assets/19718055/19622604/866d568c-98ad-11e6-9422-769fb1b2b081.jpg)

**Comment by ginold** [comment]
What browser are you using?

**Comment by stef74** [comment]
I reproduce in FF

**Comment by loicperrin** [comment]
FF 49.0.2 (last version).
Seems to be OK with Chrome.

**Comment by stef74** [comment]
I reproduce on FF

The first point for me is fixed
​

2016-10-24 9:17 GMT+02:00 ginold <notifications@github.com>:

**Comment by asaunier** [comment]
> The first point for me is fixed

It's not. In the outings advanced search page, outings are still order from the the newest to the oldest vertically (columns) but not horizontally (rows). Outings at the top of the list should be the newest, whatever the column.

@ginold do we have a solution for this?

**Comment by ginold** [comment]
not yet, I will have to look deeper into this problem.

**Comment by ginold** [comment]
It seems that it cannot be fully solved with pure CSS (http://stackoverflow.com/questions/5234749/css-floating-divs-at-variable-heights). I managed to do something like this which is not that bad: 

![screenshot from 2016-11-03 14-18-35](https://cloud.githubusercontent.com/assets/7814311/19967438/7e3e3d92-a1d0-11e6-9456-971893414c40.png)

however, as you can see, the cards are not perfectly stacked one upon another - but they are ordered from left to right.

maybe http://masonry.desandro.com/ will do the trick?

**Comment by asaunier** [comment]
> I managed to do something like this which is not that bad

Not that bad indeed. But it greatly depends on the height of the cards. In your example the cards have quite the same height. But with image cards for instance, the heights will greatly vary and make quite a lot of empty spaces appear. http://c2corgv6.demo-camptocamp.com/images

How masonry works? Would it imply a lot of new code to load and many changes in our JS code?

**Comment by ginold** [comment]
We could apply this system to outings only, the other documents not needing to have a sorted list of items?

I don't know about mansory, I will have to check it out.

**Comment by asaunier** [comment]
> the other documents not needing to have a sorted list of items?

Other document types are sorted anyway, even though not on dates (so perhaps it's not so obvious).
So this issue concerns any document type.

**Comment by tsauerwein** [comment]
> however, as you can see, the cards are not perfectly stacked one upon another - but they are ordered from left to right.

In my opinion that's not too bad. I think it is even better if the titles are on the same line, it makes it easier for your eyes.

**Comment by asaunier** [comment]
> I think it is even better if the titles are on the same line, it makes it easier for your eyes.

True

But it's a bit outdated compared to modern websites (see pinterest.com for instance) and I'm afraid it will suck for images because image cards sizes may greatly vary, see http://c2corgv6.demo-camptocamp.com/images

It really depends whether we can find a not too complicated and acceptable solution or not...

**Comment by tsauerwein** [comment]
> But it's a bit outdated compared to modern websites (see pinterest.com for instance) and I'm afraid it will suck for images because image cards sizes may greatly vary

It is not a question of outdated or not. The focus of Pinterest is on images. And for images, I agree, it would seem static.

But the cards for waypoints, routes, ... contain mainly textual information. And in this case it is easier to read if you have some structure.

**Comment by asaunier** [comment]
> And in this case it is easier to read if you have some structure.

WP, routes or outings cards heights do not vary that much, so they will remain quite aligned (especially since we don't use infinite scrolling in those pages, which would accentuate the shifts).

And I don't think that "structure" is that important for WP or routes since the sorting is not that obvious than for outings for instance (on dates).

But I notice that cards of associated documents (for a given doc type) all have the same height in the detail view pages. Should we do the same for advanced search pages?
It would not really suit for images though.

It's a bit unconsistent but what about:
* using fixed height cards for all document types except images + making sure the sorting is made on a row basis first
* using the current behaviour for images advanced search
?

**Comment by ginold** [comment]
Fixed height is very dangerous and you have already seen it - we cannot define a fixed height because of the length of the title, number of activities etc...some cards will be nearly empty, others maybe too small.

**Comment by stef74** [comment]
So what is the different option ?

**Comment by loicperrin** [comment]
In advanced search results page:
- [ ] outings have to be sorted by the date of the outing (the more recent should appear first)
- [ ] other documents have to be sorted by the date of creation (the last created document should appear first)

**Comment by loicperrin** [comment]
In advanced search results page:
- [ ] new documents do not appear. See for example http://www.demov6.camptocamp.org/waypoints/815733/fr/test-summit. Same for outings.

**Comment by asaunier** [comment]
> In advanced search results page: new documents do not appear.

@arnaud-morvan Does the ES syncer script run on the demo?
https://github.com/c2corg/v6_api#run-the-application
```
make -f config/$USER run-background-jobs-prod
make -f config/$USER run-syncer-prod
```
See https://github.com/c2corg/v6_api/issues/285

**Comment by stef74** [comment]
@loicperrin API was fixed ... please confirm this issue can be close ?

**Comment by asaunier** [comment]
@stef74 This issue has no connection with the API. @loicperrin has mentioned a refresh problem but it had nothing to do with the columns layout and should have not been mentioned in this issue.

The current issue is still valid and cannot be closed:
https://github.com/c2corg/v6_ui/issues/690#issue-181134217
> For instance with the outings: most recent outings appears in the leftmost column from top to bottom, then the next outings appear in the next column (top to bottom).

**Comment by stef74** [comment]
@loicperrin has also mentionned a probleme of refresh ... this point is blocking ... if this part is fixed we can remove the tag and let issue open

**Comment by asaunier** [comment]
The refresh problem should have not been reported here. If the "blocking" label is related to the problem, please remove it anyway.

**Comment by stef74** [comment]
Concerning the sorting it is clear ?

**Comment by loicperrin** [comment]
> The refresh problem should have not been reported here. If the "blocking" label is related to the problem, please remove it anyway

Not fixed => I have reopened issue 285 (api)
And sorting seems not to be fixed (outing 17/11 is below outing 18/11 instead of right of 18/11).

**Comment by gottferdom** [comment]
On the cards breaking only (I do not focus on sorting and all).
For Firefox and IE10+, this can be solved by using additional CSS properties:

    -webkit-column-break-inside: avoid; /* Chrome, Safari, Opera */
              page-break-inside: avoid; /* Firefox */
                   break-inside: avoid; /* IE 10+ */`

See https://css-tricks.com/almanac/properties/b/break-inside/

**Comment by fbunoz** [comment]
On FF (I don't test on another browser), the card break can be solved by adding these properties : 

```
.list-item {
    display: inline-block;
    width: 100%;
}
```

**Comment by ginold** [comment]
@brunobesson we are already using `avoid` https://github.com/c2corg/v6_ui/blob/1ebbfe4f1af7766eeca31f7494d3cbf2083355ca/less/c2corg_ui.less#L336 .

**Comment by brunobesson** [comment]
@ginold yes, you do. But the way you use the property, it is recognized only on Chrome, Safari and Opera. For Firefox and IE 10+ support, you should add the 2 other definitions I listed above. Sorry for not having been explicit enough.

**Comment by dkocich** [comment]
code inspection says that these are all "unknown CSS rules or used in a wrong context"... More info [here](http://stackoverflow.com/a/7785711) maybe?

**Comment by ginold** [comment]
After playing a little, a nice result can be achieved with `flexbox`:
![screenshot from 2016-11-28 10-14-44](https://cloud.githubusercontent.com/assets/7814311/20662470/ca0f6278-b553-11e6-9f40-58a475803eea.png)


-> easy, it's not cut in the middle, well supported and ordered from right to left.

However, the only requirements for this would be a **fixed height** of the card, as you can see in the screenshot.

The question is: is it viable? To make it play nicely, we would **need** to shorten or hide the ending part of outing's title if its too long - it's the only element in the card that has truly unpredictable length, for example with `text-overflow: ellipsis` which add `...` at the end of a text. 

Could be also number of activities, but we could maybe show the 2-3 first and add something like `and 2 others`.

What do you think?

**Comment by asaunier** [comment]
> However, the only requirements for this would be a fixed height of the card

Will be a problem especially for the image cards, since the embedded images have whatever format. Unless we use square images in all image cards?

> we would need to shorten or hide the ending part of outing's title if its too long - it's the only element in the card that has truly unpredictable length, for example with text-overflow: ellipsis which add ... at the end of a text.

Interesting

**Comment by ginold** [comment]
>  Will be a problem especially for the image cards

could be a problem, unless we make the image fit into the card, as done for the feed for example.

It could look like this (not too bad IMHO)

![screenshot from 2016-11-28 11-52-40](https://cloud.githubusercontent.com/assets/7814311/20665788/3f87c3d0-b561-11e6-876d-e30a340a4660.png)

**Comment by asaunier** [comment]
Not bad indeed!
"ellipsis" might also be needed for image titles as well.

**Comment by ginold** [comment]
So if you are ok with that, I will get a proposal PR with those changes this week.
@brunobesson, @loicperrin, @stef74, any objections, opinions?

**Comment by brunobesson** [comment]
I haven't participated in this discussion from the begining, but to me, using flexbox is a nice solution.
The only problem concerns having the same width and height for all cards, but you proposed reasonable solutions. Maybe this could be enhanced in the future, but I approve doing likewise for now.

As for images cropping, @lbesson mentioned a javascript library a while ago that produced nice results, but I can't find it. @asaunier do you remember? (anyway this would be for a later release)

**Comment by asaunier** [comment]
> As for images cropping, @lbesson mentioned a javascript library a while ago that produced nice results, but I can't find it. 

I think it was Smartcrop.js https://29a.ch/sandbox/2014/smartcrop/examples/testsuite.html

**Comment by brunobesson** [comment]
Yes that's it! Thanks

**Comment by stef74** [comment]
Sorry I have ready quicly ... and some technical point are not in my skill. But ...
Ok for fix height (many complains about dynamic heigh). 
This usse ahve two part one concerning layout ... one concerning sorting. You have fix layout , but also sorting ?

**Comment by loicperrin** [comment]
Seems to be nice. @ginold: before working on your proposal, could you give a screenshot containing cards with images and cards without images (on the same line)?

> This usse ahve two part one concerning layout ... one concerning sorting. You have fix layout , but also sorting ?

According to proposal screenshot, sorting seems to be fixed. To be tested on demo when ready.

**Comment by ginold** [comment]
By "cards without images" you mean any other type of cards (route, outing, waypoints) ?

**Comment by loicperrin** [comment]
> By "cards without images" you mean any other type of cards (route, outing, waypoints) ?

Indeed. Sorry in the same page, we cannot have cards with images and cards without images (I believed that we could have "outing cards" containing images, as in home page). So there is no problem to implement your proposal.

Cropping images in the images page is not a problem: in V5 we already have "cards with fixed heights" for images (see https://www.camptocamp.org/images).

> Could be also number of activities, but we could maybe show the 2-3 first and add something like and 2 others.

I'd prefer to avoid this for activities, but it is OK for outing titles (the best would be to display, in this case, a tooltip containing the whole title , if it is easy to add).

**Comment by stef74** [comment]
This issue is tagged Go Live ...
@loicperrin what is missing for close this issue ? 
@ginold you have plan to work on it ?

If is not realistic to do before Thursday I move in 6.1

**Comment by asaunier** [comment]
I think the main concern is that outings are sorted top to bottom on the first column, then on the second column, etc. Ditto for other document types but it is less obvious.
The right way to sort cards, is left to right then top to bottom.

**Comment by ginold** [comment]
I'm working on it right now. Not as easy as i have expected though.. :P

**Comment by stef74** [comment]
@ginold when do you think is ready ?

**Comment by ginold** [comment]
I have just finished my work. Everyone who is interested in how it could look like please see https://github.com/c2corg/v6_ui/pull/1124

**Comment by fbunoz** [comment]
I just give an example of what will be visible on prod today on a 1280px width screen : 

![sorties_v6](https://cloud.githubusercontent.com/assets/3902555/21001641/eb11ed26-bd21-11e6-8d83-6d4e75320cda.png)

The cutted box disappear with [this CSS](#issuecomment-263139791).

**Comment by ginold** [comment]
Please wait for my work to be merged, it will surely be today and available on the site soon after.

**Comment by stef74** [comment]
Ok on safari 
@loicperrin @brunobesson @desnoes could you test on other browser and close

@asaunier Probably need to push in production quickly ;-)

**Comment by loicperrin** [comment]
OK on Firefox and Chrome
