### ISSUE TITLE
document quality translation

### ISSUE THREAD

**Issue by ginold** [c2corg/v6_ui#845]
seen in french but may apply to other languages: 

"qualité du document: bonnes" probably because of "conditions: bonnes" where in english "good" is written in both cases.

**Comment by asaunier** [comment]
Are you sure your branch is up to date?
It should be fixed since "good" has been renamed to "fine" in https://github.com/c2corg/v6_common/blob/master/c2corg_common/attributes.py#L601

**Comment by dkocich** [comment]
I have it ok in site_packages in UI/API project, everything is up to date, but I have found some manually created documents with good quality, so it crashed ES syncer, etc.

I think we can still have problems with this translation unless we recreate DB and migrate again (or maybe as faster solution just change guidebook.quality_type to allow fine instead of good or at least update all 'good' values in documents)
`UPDATE guidebook.documents SET quality = 'draft' WHERE quality='good';`

**Comment by asaunier** [comment]
Perhaps you mean
> UPDATE guidebook.documents SET quality = 'fine' WHERE quality='good';
?

**Comment by asaunier** [comment]
I don't understand what you mean.
There was a conflict with quality "good", so it was renamed to "fine". The conflict is now fixed. This is the value to use now.

**Comment by dkocich** [comment]
Yes, of course. I just suggested (as a workaround for testing purposes) to just change that value in DB for now, because I do not know if it is possible to change it in already existing TYPE in DB and new migration takes too long time for me.
